name = "mailforge"
type = "javascript"
account_id = "4b05237351888b9aa815de0b5802f328"
workers_dev = true
main = "src/index.js"

# KV Namespaces for development
[[kv_namespaces]]
binding = "EMAILS"
id = "a6e5b66a9acd4ef58eece8dd47fcd1f0"

[[kv_namespaces]]
binding = "USERS"
id = "da706bb0d89a43f8aaddb7339f24d53a"

# Environment variables (development)
[env.development]
vars = { ENVIRONMENT = "development" }

# Environment variables (production)
[env.production]
name = "mailforge-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "EMAILS"
id = "a6e5b66a9acd4ef58eece8dd47fcd1f0"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "da706bb0d89a43f8aaddb7339f24d53a"
